devices:
  - name: test-pylogix
    frequency: 1
    driver: pylogix
    ip: '192.168.1.2'
    slot: 3
    route: 
      - !!python/tuple [1,3]
    data_dir: "./data/mysql1/"

    tags:
      - name: '10R60 Autogauge 1816'
        type: ping
        tag: 'AOI_0455_Op130_1816.Count'
        frequency: 300

      - name: 'Good Part Count 0455'  # name for data point
        type: counter
        data_dir: "./data/mysql1/"
        tag: 'AOI_0455_Op130_1816.Count'
        frequency: 1        # optional, defaults to device freq
        machine: 1816       # machine number for database entry
        part: "50-0455"   # a hard coded value

      - name: 'Good Part Count 9341'  # name for data point
        type: counter
        data_dir: "./data/mysql1/"
        tag: 'AOI_9341_Op130_1816.Count'
        frequency: 1        # optional, defaults to device freq
        machine: 1816       # machine number for database entry
        part: "50-9341"   # a hard coded value
