devices:
  - name: test-pylogix
    frequency: 1
    driver: pylogix
    # ip: '192.168.1.2'
    ip: '10.4.43.5'
    slot: 3
    route: 
      - !!python/tuple [1,3]
    data_dir: "./data/mysql1/"

    ### TODO: allow part type spec in device to prevent repeating on each tag
    # part: '50-9341'

    tags:
      - name: '10R80 Autogauge 1533'
        type: ping
        tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'
        frequency: 300

      - name: 'Good Part Count'  # name for data point
        type: counter
        data_dir: "./data/mysql1/"
        tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'
        frequency: .5        # optional, defaults to device freq
        machine: 1533       # machine number for database entry
        scale: 1            # number of parts made per cycle
        part: '50-9341'

      - type: reject
        reason: '10-1 Orientation Fail'
        tag: 'Program:Stn010.Part_Count[1].Bad_Part_Count'
        part: '50-9341'

      - type: reject
        reason: '10-2 Balance and Pellet Hole Fail'
        tag: 'Program:Stn010.Part_Count[2].Bad_Part_Count'
        part: '50-9341'

      - type: reject
        reason: '10-3 Window Height Fail'
        tag: 'Program:Stn010.Part_Count[3].Bad_Part_Count'
        part: '50-9341'

      - type: reject
        reason: '10-4 Spline Hole Fail'
        tag: 'Program:Stn010.Part_Count[4].Bad_Part_Count'
        part: '50-9341'

      - type: reject
        reason: '10-5 Cross Hole Fail'
        tag: 'Program:Stn010.Part_Count[5].Bad_Part_Count'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn020.Part_Count[1].Bad_Part_Count'
        reason: '20-1 Media Inspection Fail'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn020.Part_Count[3].Bad_Part_Count'
        reason: '20-2 Resonance Fail'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn020.Part_Count[2].Bad_Part_Count'
        reason: '20-3 2D Presence Fail'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn030.Part_Count[1].Bad_Part_Count'
        reason: '30-1 Probe 1 Fail'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn030.Part_Count[2].Bad_Part_Count'
        reason: '30-2 Probe 2 Fail'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn040.Part_Count[1].Bad_Part_Count'
        reason: '40-1 Bearing ID Fail'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn040.Part_Count[2].Bad_Part_Count'
        reason: '40-2 Spline OD Fail'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn040.Part_Count[3].Bad_Part_Count'
        reason: '40-3 Pinion Fail'
        part: '50-9341'

      - type: reject
        tag: 'Program:Stn040.Part_Count[9].Bad_Part_Count'
        reason: '40-4 Fail to Lower'
        part: '50-9341'


