devices:
  - name: 10R80_Offline_OP80_1527
    frequency: 1
    driver: pylogix
    ip: '192.168.1.160'
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: 1527
    part: "50-9341"

    tags:
      - name: '10R80 Off OP80 1527'
        type: ping
        tag: 'Program:MainProgram.ProdCount.ACC'
        frequency: 300

      - name: '1527 Good Part Count'
        type: counter
        tag: 'Program:MainProgram.ProdCount.ACC'
  
      # MQTT Configuration
      - name: '10R80 Offline OP80 1527'
        type: ping
        tag: 'Program:MainProgram.ProdCount.ACC'
        data_dir: "./data/mqtt/"
        frequency: 5

      - name: '1527 Good Part Count'
        type: counter
        tag: 'Program:MainProgram.ProdCount.ACC'
        data_dir: "./data/mqtt/"
  
