devices:
  - name: 10R80_UpLift_BushingPress_1552_PLC
    frequency: 1
    driver: pylogix
    ip: '192.168.1.10'
    data_dir: "./data/mysql1/"

    tags:
      - name: '10R80 UpLift BushPress 1552'
        type: ping
        tag: 'ProdCount.ACC'
        frequency: 300

      - name: 'Good Part Count'  # name for data point
        type: counter
        data_dir: "./data/mysql1/"
        tag: 'ProdCount.ACC'
        frequency: 1        # optional, defaults to device freq
        machine: 1552       # machine number for database entry
        scale: 1            # number of parts made per cycle
        part: "50-9341"   # a hard coded value

      # - name: 'Reject Part Count'  # name for data point
      #   type: counter
      #   data_dir: "./data/mysql1/"

      #   tag: 'ProdCountReject.ACC'
      #   frequency: 1        # optional, defaults to device freq

      #   machine: 1552REJ       # machine number for database entry
      #   scale: 1            # number of parts made per cycle

      #   part: "50-9341"   # a hard coded value
