devices:
  - name: 10R80_UpLift_BushingPress_1552_PLC
    frequency: 1
    driver: pylogix
    ip: '192.168.1.10'
    data_dir: "./data/mysql1/"
    part: "50-9341"

    tags:
      - name: '10R80 UpLift BushPress 1552'
        type: ping
        tag: 'ProdCount.ACC'
        frequency: 300

      - name: 'Good Part Count'
        type: counter
        tag: 'ProdCount.ACC'
        machine: 1552

      - type: reject
        reason: 'All rejects'
        tag: 'ProdCountReject.ACC'
        machine: 1552
