devices:
  - name: 10R80_MainLine_OP50_1532
    frequency: 1
    driver: pylogix
    ip: '192.168.1.180'
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: 1532
    part: "50-9341"

    tags:
      - name: '10R80 Main OP50 1532'
        type: ping
        tag: 'Program:MainProgram.ProdCount.acc'
        frequency: 300

      - name: '1532 Good Part Count'
        type: counter
        tag: 'Program:MainProgram.ProdCount.acc'

      - name: '1532 Good Part Count'
        type: reject
        tag: 'Program:MainProgram.ProdCountReject.ACC'
  
      # MQTT Configuration
      - name: '10R80 Main OP50 1532'
        type: ping
        tag: 'Program:MainProgram.ProdCount.acc'
        data_dir: "./data/mqtt/"
        frequency: 5

      - name: '1532 Good Part Count'
        type: counter
        tag: 'Program:MainProgram.ProdCount.ACC'
        data_dir: "./data/mqtt/"

      - name: '1532 Reject Count'
        type: reject
        tag: 'Program:MainProgram.ProdCountReject.ACC'
        data_dir: "./data/mqtt/"
  
