devices:
  - name: 10R80_Offline_OP40_1525
    frequency: 1
    driver: pylogix
    ip: '192.168.1.130'
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: 1525
    part: "50-9341"

    tags:
      - name: '10R80 Offline OP40 1525'
        type: ping
        tag: 'Program:MainProgram.ProdCount.ACC'
        frequency: 300

      - name: '1525 Good Part Count'
        type: counter
        tag: 'Program:MainProgram.ProdCount.ACC'
        scale: 4
  
      # MQTT Configuration
      - name: '10R80 Offline OP40 1525'
        type: ping
        tag: 'Program:MainProgram.ProdCount.ACC'
        data_dir: "./data/mqtt/"
        frequency: 5

      - name: '1525 Good Part Count'
        type: counter
        tag: 'Program:MainProgram.ProdCount.ACC'
        data_dir: "./data/mqtt/"

