devices:
  - name: 10R80_BushPress_1513
    frequency: 1
    driver: pylogix
    ip: '192.168.1.1'
    data_dir: "./data/mysql1/"

    tags:
      - name: '10R80 BushPress 1513' # 1511
        type: ping
        tag: 'ProdCount.ACC'
        frequency: 300
      - name: '1513 Good Part Count'  # name for data point
        type: counter
        tag: 'ProdCount.ACC'
        frequency: 1        # optional, defaults to device freq
        machine: 1513       # machine number for database entry
        scale: 1            # number of parts made per cycle
        part: "50-9341"     # a hard coded value
      - name: '1513 Reject Count'  # name for data point
        type: counter
        tag: 'ProdCountReject.ACC'
        frequency: 1        # optional, defaults to device freq
        machine: 1513REJ       # machine number for database entry
        scale: 1            # number of parts made per cycle
        part: "50-9341"     # a hard coded value
