devices:
  - name: 10R80_OP40_1501
    frequency: 1
    driver: pylogix
    ip: '192.168.1.80'
    data_dir: "./data/mysql1/"

    tags:
      - name: '10R80 OP40_Cell2 1501'
        type: ping
        tag: 'Program:MainProgram.ProdCount.acc'
        frequency: 300

      - name: 'Good Part Count'  # name for data point
        type: counter
        data_dir: "./data/mysql1/"

        tag: 'Program:MainProgram.ProdCount.acc'
        frequency: 1        # optional, defaults to device freq

        machine: 1501       # machine number for database entry
        scale: 2            # number of parts made per cycle

        part: "50-9341"   # a hard coded value
