devices:
  - name: 10R80_Offline_OP110_PLC
    frequency: 1
    driver: pylogix
    ip: '192.168.1.180'
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: 1528
    part: "50-9341"

    tags:
      - name: '10R80 Offline OP110'
        type: ping
        tag: 'Program:MainProgram.ProdCount.acc'
        frequency: 300

      - name: '1528 Good Part Count'
        type: counter
        tag: 'Program:MainProgram.ProdCount.acc'

      - type: reject
        reason: 'Air Sensing'
        tag: 'ProdCountRej.acc'
        
      # MQTT Configs
      - name: '10R80 Offline OP110'
        type: ping
        data_dir: "./data/mqtt/"
        tag: 'Program:MainProgram.ProdCount.acc'
        frequency: 5

      - name: '1528 Good Part Count'
        type: counter
        data_dir: "./data/mqtt/"
        tag: 'Program:MainProgram.ProdCount.acc'

      - name: '1528 Airsensing Reject'
        type: reject
        data_dir: "./data/mqtt/"
        reason: 'Air Sensing'
        tag: 'ProdCountRej.acc'
 