devices:
  - name: 10R80_BushPress_1513
    frequency: 1
    driver: pylogix
    ip: '192.168.1.1'
    data_dir: "./data/mysql1/"

    tags:
      - name: '10R80 BushPress 1513'
        type: ping
        tag: 'ProdCount.ACC'
        frequency: 300

      - name: '1513 Good Part Count'
        type: counter
        tag: 'ProdCount.ACC'
        frequency: 1
        machine: 1513
        part: "50-9341"

        type: reject
        reason: 'All Rejects'
        tag: 'ProdCountReject.ACC'
        machine: 1513
        part: "50-9341"
