devices:
  - name: 10R80_BushPress_1513
    frequency: 1
    driver: pylogix
    ip: '192.168.1.1'
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: 1513
    part: "50-9341"

    tags:
      - name: '10R80 BushPress 1513'
        type: ping
        tag: 'ProdCount.ACC'
        frequency: 300

      - name: '1513 Good Part Count'
        type: counter
        tag: 'ProdCount.ACC'
  
      - name: '1513 Reject Count'
        type: reject
        reason: 'All Rejects'
        tag: 'ProdCountReject.ACC'

      # MQTT Configuration
      - name: '10R80 BushPress 1513'
        type: ping
        tag: 'ProdCount.ACC'
        data_dir: "./data/mqtt/"
        frequency: 5

      - name: '1513 Good Part Count'
        type: counter
        tag: 'ProdCount.ACC'
        data_dir: "./data/mqtt/"
  
      - name: '1513 Reject Count'
        type: reject
        reason: 'All Rejects'
        tag: 'ProdCountReject.ACC'
        data_dir: "./data/mqtt/"
