devices:
  - name: test-pylogix
    frequency: .5
    driver: pylogix
    ip: '192.168.1.2'
    slot: 3
    route: 
      - !!python/tuple [1,3]
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: '1533'
    part: '50-9341'

    # part_number_tag: 'Program:MainProgram.ProdCountpartDINT'
    # part_dict:
    #   0: '50-0455'
    #   1: '50-9341'

    tags:
      # mysql ping
      - name: '10R80 Autogauge 1533'
        type: ping
        tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'
        frequency: 300

      # mqtt heartbeat
      # not needed... tracking 1505 and 1534 directly
      # - name: '10R80 Autogauge 1533'
      #   type: ping
      #   data_dir: "./data/mqtt/"
      #   tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'
      #   frequency: 5

      # mysql good part count
      - name: 'Good Part Count'
        type: counter
        tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'

      # mqtt good part count
      # not needed... tracking 1505 and 1534 directly
      # - name: 'Good Part Count'
      #   type: counter
      #   tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'
      #   frequency: .5

      # mysql rejects
      - type: reject
        reason: '10-2 Balance and Pellet Hole Fail'
        tag: 'Program:Stn010.Part_Count[2].Bad_Part_Count'

      - type: reject
        reason: '10-3 Window Height Fail'
        tag: 'Program:Stn010.Part_Count[3].Bad_Part_Count'

      - type: reject
        reason: '10-4 Spline Hole Fail'
        tag: 'Program:Stn010.Part_Count[4].Bad_Part_Count'

      - type: reject
        reason: '10-5 Cross Hole Fail'
        tag: 'Program:Stn010.Part_Count[5].Bad_Part_Count'

      - type: reject
        tag: 'Program:Stn020.Part_Count[1].Bad_Part_Count'
        reason: '20-1 Media Inspection Fail'

      - type: reject
        tag: 'Program:Stn020.Part_Count[3].Bad_Part_Count'
        reason: '20-2 Resonance Fail'

      - type: reject
        tag: 'Program:Stn020.Part_Count[2].Bad_Part_Count'
        reason: '20-3 2D Presence Fail'

      - type: reject
        tag: 'Program:Stn030.Part_Count[1].Bad_Part_Count'
        reason: '30-1 Probe 1 Fail'

      - type: reject
        tag: 'Program:Stn030.Part_Count[2].Bad_Part_Count'
        reason: '30-2 Probe 2 Fail'

      - type: reject
        tag: 'Program:Stn040.Part_Count[1].Bad_Part_Count'
        reason: '40-1 Bearing ID Fail'

      - type: reject
        tag: 'Program:Stn040.Part_Count[2].Bad_Part_Count'
        reason: '40-2 Spline OD Fail'

      - type: reject
        tag: 'Program:Stn040.Part_Count[3].Bad_Part_Count'
        reason: '40-3 Pinion Fail'

      - type: reject
        tag: 'Program:Stn040.Part_Count[9].Bad_Part_Count'
        reason: '40-4 Fail to Lower'

      - type: reject
        tag: 'Spline1Fail.ACC'
        reason: '50-1 Spline Gauge Fail Cell 1'

      - type: reject
        tag: 'Spline2Fail.ACC'
        reason: '50-1 Spline Gauge Fail Cell 2'


      # # mqtt rejects
      # - type: reject
      #   reason: '10-2 Balance and Pellet Hole Fail'
      #   tag: 'Program:Stn010.Part_Count[2].Bad_Part_Count'

      # - type: reject
      #   reason: '10-3 Window Height Fail'
      #   tag: 'Program:Stn010.Part_Count[3].Bad_Part_Count'

      # - type: reject
      #   reason: '10-4 Spline Hole Fail'
      #   tag: 'Program:Stn010.Part_Count[4].Bad_Part_Count'

      # - type: reject
      #   reason: '10-5 Cross Hole Fail'
      #   tag: 'Program:Stn010.Part_Count[5].Bad_Part_Count'

      # - type: reject
      #   tag: 'Program:Stn020.Part_Count[1].Bad_Part_Count'
      #   reason: '20-1 Media Inspection Fail'

      # - type: reject
      #   tag: 'Program:Stn020.Part_Count[3].Bad_Part_Count'
      #   reason: '20-2 Resonance Fail'

      # - type: reject
      #   tag: 'Program:Stn020.Part_Count[2].Bad_Part_Count'
      #   reason: '20-3 2D Presence Fail'

      # - type: reject
      #   tag: 'Program:Stn030.Part_Count[1].Bad_Part_Count'
      #   reason: '30-1 Probe 1 Fail'

      # - type: reject
      #   tag: 'Program:Stn030.Part_Count[2].Bad_Part_Count'
      #   reason: '30-2 Probe 2 Fail'

      # - type: reject
      #   tag: 'Program:Stn040.Part_Count[1].Bad_Part_Count'
      #   reason: '40-1 Bearing ID Fail'

      # - type: reject
      #   tag: 'Program:Stn040.Part_Count[2].Bad_Part_Count'
      #   reason: '40-2 Spline OD Fail'

      # - type: reject
      #   tag: 'Program:Stn040.Part_Count[3].Bad_Part_Count'
      #   reason: '40-3 Pinion Fail'

      # - type: reject
      #   tag: 'Program:Stn040.Part_Count[9].Bad_Part_Count'
      #   reason: '40-4 Fail to Lower'

      # - type: reject
      #   tag: 'Spline1Fail.ACC'
      #   reason: '50-1 Spline Gauge Fail Cell 1'

      # - type: reject
      #   tag: 'Spline2Fail.ACC'
      #   reason: '50-1 Spline Gauge Fail Cell 2'

  - name: 1505 Laser
    frequency: 1
    driver: pylogix
    ip: '192.168.1.67'
    data_dir: "./data/mysql/"

    tags:
      - name: '1505 Laser'
        type: ping
        frequency: 300

      - name: '10R80 Laser 1505'
        type: ping
        data_dir: "./data/Tmqtt/"
        tag: 'ProdCountGood.ACC'
        frequency: 5

      - name: 'Good Part Count'
        type: counter
        tag: 'ProdCountGood.ACC'
        frequency: .5
        machine: 1505
        part_number_tag: 'RunningPartNumber'

      - type: reject
        reason: 'Laser Failed'
        tag: 'ProdCountReject.ACC'
        machine: 1505
        part_number_tag: 'RunningPartNumber'


  - name: 1534 Laser
    frequency: 1
    driver: pylogix
    ip: '192.168.1.61'
    data_dir: "./data/mysql/"

    tags:
      - name: '1534 Laser'
        type: ping
        tag: 'ProdCountGood.ACC'
        frequency: 300

      # - name: '10R80 Autogauge 1533'
      #   type: ping
      #   data_dir: "./data/mqtt/"
      #   tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'
      #   frequency: 5

      - name: 'Good Part Count'
        type: counter
        tag: 'ProdCountGood.ACC'
        frequency: .5
        machine: 1534
        part_number_tag: 'RunningPartNumber'

      - type: reject
        reason: 'Laser Failed'
        tag: 'ProdCountReject.ACC'
        machine: 1534
        part_number_tag: 'RunningPartNumber'


