devices:
  - name: 10R80_Main_OP60_1509
    frequency: 1
    driver: pylogix
    ip: '192.168.1.34'
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: 1509
    part: "50-9341"

    tags:
      - name: '10R80 Main OP60 1509'
        type: ping
        tag: 'Program:MainProgram.ProdCount.ACC'
        frequency: 300

      - name: '1509 Good Part Count'
        type: counter
        scale: 2
        tag: 'Program:MainProgram.ProdCount.ACC'
  
      # MQTT Configuration
      - name: '10R80 Main OP60 1509'
        type: ping
        tag: 'Program:MainProgram.ProdCount.ACC'
        data_dir: "./data/mqtt/"
        frequency: 5

      - name: '1509 Good Part Count'
        type: counter
        scale: 2
        tag: 'Program:MainProgram.ProdCount.ACC'
        data_dir: "./data/mqtt/"
  
