devices:
  - name: Press 245
    frequency: .5
    driver: modbus
    ip: '10.4.42.122'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql1/"

    tags:
      - name: 'Press 245'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
          length: 2
        frequency: 300

      - name: 'Press 245 Counter'  # name for data point
        type: ADAM_counter
        machine: 245
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0 
          length: 2
        part: "compact"

  - name: Press 280
    frequency: .5
    driver: modbus
    ip: '10.4.45.50'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql1/"

    tags:
      - name: 'Press 280'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
        frequency: 300

      - name: 'Press 280 counter'  # name for data point
        type: ADAM_counter
        machine: 280        # machine number for database entry
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0  # 
          length: 2   # number of registers to read
        part: "compact"

  - name: Press 261 262 263
    frequency: .5
    driver: modbus
    ip: '10.4.42.125'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql1/"

    tags:
      - name: 'Carrier Line Presses'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
        frequency: 300

      - name: 'Press 261'  # name for data point
        type: ADAM_counter
        machine: 261        # machine number for database entry
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0  # 
          length: 2   # number of registers to read
        part: "compact"

      - name: 'Press 262'  # name for data point
        type: ADAM_counter
        machine: 262        # machine number for database entry
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 2  # 
          length: 2   # number of registers to read
        part: "compact"

      - name: 'Press 263'  # name for data point
        type: ADAM_counter
        machine: 263        # machine number for database entry
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 4  # 
          length: 2   # number of registers to read
        part: "compact"

  - name: Press 272
    frequency: .5
    driver: modbus
    ip: '10.4.45.55'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql1/"

    tags:
      - name: 'Press 272'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 14
          length: 2
        frequency: 300

      - name: 'Press 272 Counter'  # name for data point
        type: ADAM_counter
        machine: 272
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 14 
          length: 2
        part: "compact"

  - name: Press 273
    frequency: .5
    driver: modbus
    ip: '10.4.45.56'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql1/"

    tags:
      - name: 'Press 273'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 14
          length: 2
        frequency: 300

      - name: 'Press 273 Counter'  # name for data point
        type: ADAM_counter
        machine: 273
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 14 
          length: 2
        part: "compact"
