devices:
  - name: 10R80 OP10-20 Mainline 1504 1506 1519 1520
    frequency: 1
    driver: modbus
    ip: '10.4.42.183'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"
    part: "50-9341"

    tags:
      - name: '10R80 OP20 Main 1504 1506 1519 1520'
        type: ping
        register:
          type: H
          address: 6
          length: 2
        frequency: 300

      - name: '1504 Counter'
        type: ADAM_counter
        machine: 1504
        register:
          type: H
          address: 6 
          length: 2
        part: "50-9341"

      - name: '1506 Counter'
        type: ADAM_counter
        machine: 1506
        register:
          type: H
          address: 4
          length: 2
        part: "50-9341"

      - name: '1519 Counter'
        type: ADAM_counter
        machine: 1519
        register:
          type: H
          address: 0
          length: 2
        part: "50-9341"

      - name: '1520 Counter'
        type: ADAM_counter
        machine: 1520
        register:
          type: H
          address: 2
          length: 2
        part: "50-9341"

      #JEMES configs
      - name: '10R80 OP20 Main 1504 1506 1519 1520'
        type: ping
        register:
          type: H
          address: 6
          length: 2
        frequency: 5
        data_dir: "./data/mqtt/"

      - name: '1504 Part Counter'
        type: ADAM_counter
        machine: 1504
        register:
          type: H
          address: 6 
          length: 2
        data_dir: "./data/mqtt/"
 
      - name: '1506 Part Counter'
        type: ADAM_counter
        machine: 1506
        register:
          type: H
          address: 4 
          length: 2
        data_dir: "./data/mqtt/"

      - name: '1519 Part Counter'
        type: ADAM_counter
        machine: 1519
        register:
          type: H
          address: 0
          length: 2
        data_dir: "./data/mqtt/"

      - name: '1520 Part Counter'
        type: ADAM_counter
        machine: 1520
        register:
          type: H
          address: 2
          length: 2
        data_dir: "./data/mqtt/"

  - name: 10R80 OP10-20 Offline 1518 1521 1522 1523
    frequency: 1
    driver: modbus
    ip: '10.4.45.51'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    part: "50-9341"

    tags:
      - name: '10R60 OP10-20 1518 1521 1522 1523'
        type: ping
        register:
          type: H
          address: 0
          length: 2
        frequency: 300

      - name: '1523 Part Counter'
        type: ADAM_counter
        machine: 1523
        register:
          type: H
          address: 0 
          length: 2

      - name: '1521 Part Counter'
        type: ADAM_counter
        machine: 1521
        register:
          type: H
          address: 2 
          length: 2

      - name: '1518 Part Counter'
        type: ADAM_counter
        machine: 1518
        register:
          type: H
          address: 4 
          length: 2

      - name: '1522 Part Counter'
        type: ADAM_counter
        machine: 1522
        register:
          type: H
          address: 6 
          length: 2

      #JEMES configs
      - name: '10R60 OP10-20 1518 1521 1522 1523'
        type: ping
        register:
          type: H
          address: 0
          length: 2
        frequency: 300
        data_dir: "./data/mqtt/"

      - name: '1523 Part Counter'
        type: ADAM_counter
        machine: 1523
        register:
          type: H
          address: 0 
          length: 2
        data_dir: "./data/mqtt/"
 
      - name: '1521 Part Counter'
        type: ADAM_counter
        machine: 1521
        register:
          type: H
          address: 2 
          length: 2
        data_dir: "./data/mqtt/"

      - name: '1518 Part Counter'
        type: ADAM_counter
        machine: 1518
        register:
          type: H
          address: 4 
          length: 2
        data_dir: "./data/mqtt/"

      - name: '1522 Part Counter'
        type: ADAM_counter
        machine: 1522
        register:
          type: H
          address: 6 
          length: 2
        data_dir: "./data/mqtt/"

  - name: Press 245
    frequency: 1
    driver: modbus
    ip: '10.4.42.122'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"

    tags:
      - name: 'Press 245'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
          length: 2
        frequency: 300

      - name: 'Press 245 Counter'  # name for data point
        type: ADAM_counter
        machine: 245
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0 
          length: 2
        part: "compact"

  - name: Press 280
    frequency: 1
    driver: modbus
    ip: '10.4.45.50'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"

    tags:
      - name: 'Press 280'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
        frequency: 300

      - name: 'Press 280 counter'  # name for data point
        type: ADAM_counter
        machine: 280        # machine number for database entry
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0  # 
          length: 2   # number of registers to read
        part: "compact"

  - name: Press 261 262 263
    frequency: 1
    driver: modbus
    ip: '10.4.42.125'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"

    tags:
      - name: 'Carrier Line Presses'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
        frequency: 300

      - name: 'Press 261'  # name for data point
        type: ADAM_counter
        machine: 261        # machine number for database entry
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0  # 
          length: 2   # number of registers to read
        part: "compact"

      - name: 'Press 262'  # name for data point
        type: ADAM_counter
        machine: 262        # machine number for database entry
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 2  # 
          length: 2   # number of registers to read
        part: "compact"

      - name: 'Press 263'  # name for data point
        type: ADAM_counter
        machine: 263        # machine number for database entry
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 4  # 
          length: 2   # number of registers to read
        part: "compact"

  - name: Press 272
    frequency: 1
    driver: modbus
    ip: '10.4.45.55'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"

    tags:
      - name: 'Press 272'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 14
          length: 2
        frequency: 300

      - name: 'Press 272 Counter'  # name for data point
        type: ADAM_counter
        machine: 272
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 14 
          length: 2
        part: "compact"

  - name: Press 273
    frequency: 1
    driver: modbus
    ip: '10.4.45.56'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"

    tags:
      - name: 'Press 273'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 14
          length: 2
        frequency: 300

      - name: 'Press 273 Counter'  # name for data point
        type: ADAM_counter
        machine: 273
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 14 
          length: 2
        part: "compact"

  - name: Optimized Machining
    frequency: 1
    driver: modbus
    ip: '10.4.42.123'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"

    tags:
      - name: 'Optimized Machining'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
          length: 2
        frequency: 300

      - name: '624 Counter'  # name for data point
        type: ADAM_counter
        machine: 624
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0 
          length: 2
        part: "Magna"

      - name: '624 Counter'  # name for data point
        type: ADAM_counter
        machine: 619
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 2 
          length: 2
        part: "Magna"

      - name: '624 Counter'  # name for data point
        type: ADAM_counter
        machine: 618
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 4 
          length: 2
        part: "Magna"

      - name: '624 Counter'  # name for data point
        type: ADAM_counter
        machine: 575
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 6 
          length: 2
        part: "Magna"

  - name: 10R60 OP10-20 Machining
    frequency: 1
    driver: modbus
    ip: '10.4.42.189'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql/"

    tags:
      - name: '10R60 OP10-20 1800 1801 1802'
        type: ping
        register:
          type: H
          address: 0
          length: 2
        frequency: 300

      - name: '1800 Part Counter'
        type: ADAM_counter
        machine: 1800
        register:
          type: H
          address: 0 
          length: 2
        part: "50-0455"

      - name: '1801 Part Counter'
        type: ADAM_counter
        machine: 1801
        register:
          type: H
          address: 2 
          length: 2
        part: "50-0455"

      - name: '1802 Part Counter'
        type: ADAM_counter
        machine: 1802
        register:
          type: H
          address: 4 
          length: 2
        part: "50-0455"
