devices:
  - name: Press 245
    frequency: 1
    driver: modbus
    ip: '10.4.42.122'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql1/"

    tags:
      - name: 'Press 245'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
        frequency: 300
      - name: 'test-modbus-count1'  # name for data point
        type: ADAM_counter
        machine: 245        # machine number for database entry
        frequency: 1        # optional, defaults to device freq
        scale: 1            # number of parts made per cycle
        register:     # the counter register
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0  # 
          length: 2   # number of registers to read
        part: "compact"


  - name: Optimized Machining
    frequency: 1
    driver: modbus
    ip: '10.4.42.123'
    port: 502
    unit_id: 0              
    data_dir: "./data/mysql1/"

    tags:
      - name: 'Optim1zed Machining'
        type: ping
        register:
          type: H  # Register type, H = Holding Reg, D = discrete input contact
          address: 0
        frequency: 300

      - name: 'Maching 624'
        type: ADAM_counter
        machine: 624
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 0 
          length: 2
        part: "magna"

      - name: 'Maching 619'
        type: ADAM_counter
        machine: 619
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 2 
          length: 2
        part: "magna"

      - name: 'Maching 618'
        type: ADAM_counter
        machine: 618
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 4 
          length: 2
        part: "magna"

      - name: 'Maching 575'
        type: ADAM_counter
        machine: 575
        register:
          type: H     # Register type, H = Holding Reg, D = discrete input contact
          address: 6 
          length: 2
        part: "magna"

