targets:
  - name: emqx-mqtt
    driver: mqtt
    frequency: 5
    ip: "10.4.10.176"
    port: 1883
    client_id: f'mqtt-10-4-10-176'
    data_dir: ./data/mqtt/

  - name: pmdsdata3-1
    frequency: 5
    driver: mysql
    dbconfig:
      database: prodrptdb
      user: stuser
      password: stp383
      host: 10.4.1.224
      port: 3306
    data_dir: ./data/mysql/

