devices:
  - name: laser_1505
    frequency: 1
    driver: pylogix
    ip: '10.4.43.202'
    slot: 3
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: '1505'
    part: "50-9341"

    tags:
      - name: 'Laser 1505'
        type: ping
        tag: 'ProdCountGood.ACC'
        frequency: 300

      - name: 'Laser 1505'
        type: ping
        data_dir: "./data/mqtt/"
        tag: 'ProdCountGood.ACC'
        frequency: 5

      - name: 'good part count'
        type: counter
        data_dir: "./data/mqtt/"
        tag: 'ProdCountGood.ACC'


  - name: laser_1534
    frequency: 1
    driver: pylogix
    ip: '10.4.43.201'
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: 1534
    part: "50-9341"

    tags:
      - name: 'Laser 1534'
        type: ping
        tag: 'ProdCountGood.ACC'
        frequency: 300

      - name: 'Laser 1534'
        type: ping
        data_dir: "./data/mqtt/"
        tag: 'ProdCountGood.ACC'
        frequency: 5

      - name: 'Good part count'
        type: counter
        data_dir: "./data/mqtt/"
        tag: 'ProdCountGood.ACC'

  - name: 10R80 Autogauge 1533 
    frequency: .5
    driver: pylogix
    ip: '10.4.43.5'
    slot: 3
    route: 
      - !!python/tuple [1,3]
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: '1505'
    part: "50-9341"

    # part_number_tag: 'Program:MainProgram.ProdCountpartDINT'
    # part_dict:
    #   0: '50-0455'
    #   1: '50-9341'


    tags:
      - name: '10R80 Autogauge 1533'
        type: ping
        tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'
        frequency: 300

      # - name: 'Good Part Count'
      #   type: counter
      #   tag: 'Program:Production.ProductionData.DailyCounts.DailyGoodTotal'
      #   frequency: .5
      #   machine: 1533
      #   scale: 1
