targets:
  # - name: litmus-mqtt
  #   driver: mqtt
  #   frequency: 5
  #   ip: "10.4.1.234"
  #   port: 1883
  #   client_id: f'mqtt-pub1'
  #   # username: 'emqx'
  #   # password: 'public'
  #   data_dir: ./temp/mqtt1/

  # - name: litmus-mqtt
  #   driver: mqtt
  #   frequency: 5
  #   ip: "10.4.1.234"
  #   port: 1883
  #   client_id: f'mqtt-pub2'
  #   # username: 'emqx'
  #   # password: 'public'
  #   data_dir: ./temp/mqtt2/

  - name: pmdsdata3-1
    frequency: 5
    driver: mysql
    dbconfig:
      database: prodrptdb
      user: stuser
      password: stp383
      host: 10.4.1.224
      port: 3306
    data_dir: ./temp/mysql1/

  - name: pmdsdata3-2
    frequency: 5
    driver: mysql
    dbconfig:
      database: prodrptdb
      user: stuser
      password: stp383
      host: 10.4.1.224
      port: 3306
    data_dir: ./temp/mysql2/
