
devices:
  - name: laser_1505
    frequency: 1
    driver: pylogix
    ip: '10.4.43.202'
    slot: 3
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: '10R80'
    machine: '1505'

    tags:
      - name: 'Laser 1505'
        type: ping
        tag: 'ProdCountGood.ACC'
        frequency: 300

      - name: 'Laser 1505'
        type: ping
        data_dir: "./data/mqtt/"
        tag: 'ProdCountGood.ACC'
        frequency: 5

      - name: 'good part count'
        type: counter
        data_dir: "./data/mqtt/"
        tag: 'ProdCountGood.ACC'
        line: "10R80"
        part: "50-9341"
        machine: 1505


  - name: laser_1534
    frequency: 1
    driver: pylogix
    ip: '10.4.43.201'
    data_dir: "./data/mysql/"

    tags:
      - name: 'Laser 1534'
        type: ping
        tag: 'ProdCountGood.ACC'
        frequency: 300

      - name: 'Laser 1534'
        type: ping
        data_dir: "./data/mqtt/"
        tag: 'ProdCountGood.ACC'
        frequency: 5
        organization: 'JEC'
        site: 'Stratford'
        line: '10R80'
        machine: 1534


      - name: 'Good part count'
        type: counter
        data_dir: "./data/mqtt/"
        tag: 'ProdCountGood.ACC'
        organization: 'JEC'
        site: 'Stratford'
        line: '10R80'
        part: "50-9341"
        machine: 1534

