devices:
  - name: Trilobe Assembler 859
    frequency: 1
    driver: pylogix
    ip: '192.168.1.10'
    data_dir: "./data/mysql/"

    tags:
      - name: 'Trilobe Assembler 859'
        type: ping
        tag: 'good_part_counter_5810.ACC'
        frequency: 300
        # counters are miss labled in plc
      - name: '1467 Good Part Count'
        type: counter
        data_dir: "./data/mysql/"
        tag: 'good_part_counter_5810.ACC'
        machine: 859
        part: 50-1467
      - name: '5710 Good Part Count'
        type: counter
        data_dir: "./data/mysql/"
        tag: 'good_part_counter_5710.ACC'
        machine: 859
        part: 50-5710
      - name: '3050 Good Part Count'
        type: counter
        data_dir: "./data/mysql/"
        tag: 'good_part_counter_6549.ACC'
        machine: 859
        part: 50-3050
      - name: '7875 Good Part Count'
        type: counter
        data_dir: "./data/mysql/"
        tag: 'good_part_counter_7875.ACC'
        machine: 859
        part: 50-7875

