devices:
  - name: 'Trilobe Slurry 742'
    frequency: 1
    driver: pylogix
    ip: '192.168.1.1'
    data_dir: "./data/mysql/"
    organization: 'JEC'
    site: 'Stratford'
    line: 'Trilobe'
    machine: '742'


    tags:
#MYSQL
      - name: 'Trilobe Slurry 742'
        type: ping
        tag: 'ProdCount.ACC'
        frequency: 300

      - name: 'Good Part Count'
        type: counter
        data_dir: "./data/mysql/"
        tag: 'ProdCount.ACC'
        machine: 742
        part: "50-1467"


# MQTT
      - name: 'Trilobe Slurry 6742'
        type: ping
        data_dir: "./data/mqtt/"
        tag: 'ProdCount.ACC'
        frequency: 5

      - name: 'Good Part Count'
        type: counter
        data_dir: "./data/mqtt/"
        tag: 'ProdCount.ACC'
        machine: 742
        part: "50-1467"

      - name: 'Reject Part Count'
        type: counter
        data_dir: "./data/mqtt/"
        tag: 'ProdCountRej.ACC'
        machine: 742
        part: "50-1467"
        reason: "Vision Reject"
